### ISSUE TITLE
Change the title to rms-open-letter.github.io - something

### ISSUE THREAD

**Issue by shenlebantongying** [M-i-k-o-t-o/rms-open-letter.github.io-removed-issues#1]
For search engine understant it better
![image](https://user-images.githubusercontent.com/20123683/112593573-10db5d80-8dde-11eb-90c4-74302b58748f.png)
![image](https://user-images.githubusercontent.com/20123683/112593641-28b2e180-8dde-11eb-833c-cae7fa0aafa6.png)

**Comment by M-i-k-o-t-o** [comment]
fixed, thanks!
